with Ada.Directories;
package body size_generator is 

    procedure Generate is
        File : FIle_Type;
    begin
        if Ada.Directories.Exists (filename) then
            Open (File => File, Mode => Out_File, Name => Filename);
        else
            Create (File => File, Mode => Out_File, Name => Filename);
        end if;
        Put_Line(File, "-- This file was generated by configuration program.");
        Put_Line(File, "-- Do not modify it directly!");
        Put_line(File, "package ffmpeg.internal.csizes is");
        Put_line(File, "AVCodec_Size : constant :=" &  Integer'Image (8 * Integer (AVCodec_Context)) & ";");
        Put_line(File, "AVPacket_Size : constant :=" &  Integer'Image (8 * Integer (AVPacket)) & ";");
        Put_line(File, "AVPicture_Size : constant :=" &  Integer'Image (8 * Integer (AVPicture)) & ";");
        Put_line(File, "AVSubtitleRect_Size : constant :=" &  Integer'Image (8 * Integer (AVSubtitleRect)) & ";");
        Put_line(File, "AVSubtitle_Size : constant :=" &  Integer'Image (8 * Integer (AVSubtitle)) & ";");
        Put_line(File, "AVFrame_Size : constant :=" &  Integer'Image (8 * Integer (AVFrame)) & ";");
        Put_line (File, "end ffmpeg.internal.csizes;");
        Close (File);
    exception
        when others =>
            if Is_Open (File) then
                CLose (File);
            end if;
    end Generate;
end size_generator; 

